### ISSUE TITLE
Criar arquivos txt do 20 ao 30

### ISSUE THREAD

**Issue by orlandosaraivajr** [tutorsaraiva/des_serv_1_2021_1sem#2]
Acredito que possa ser interessante ter um novo bloco de arquivos texto.
![Captura de tela de 2021-02-15 21-46-56](https://user-images.githubusercontent.com/2480421/108005386-5a62ac80-6fd7-11eb-85e1-1b119f4fc3fc.png)

**Comment by tutorsaraiva** [comment]
Melhor não... Deixa como está....
